services:
  scamhunter_db:
    image: postgres:15-alpine
    container_name: scamhunter_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: scamhunter_db
    ports:
      - "5436:5432"
    volumes:
      - scamhunter_pg_data:/var/lib/postgresql/data

volumes:
  scamhunter_pg_data:
